### ISSUE TITLE
切换主题出现问题

### ISSUE THREAD

**Issue by lzx722** [pcrbot/YoCool-Console#11]
有两个问题，首先第一个问题是主题2下载404，应该上没有做好吧。第二个问题是切换不同的主题的时候，会先删除public文件夹，然后再安装的时候没有新建一个public文件夹，然后报错``FileNotFoundError: [Errno 2] No such file or directory: './hoshino/modules/yobot/yobot/src/client/public'``。如果主题2没做好的话建议先禁用切换主题

**Comment by lzx722** [comment]
log复制错了，是``FileNotFoundError: [Errno 2] No such file or directory: '/root/yobot/src/client/public'
 ``，不过不影响表达的意思的

**Comment by A-kirami** [comment]
已在新版本中修复该问题
