### ISSUE TITLE
安装插件的小bug

### ISSUE THREAD

**Issue by yuban01652** [pcrbot/YoCool-Console#2]
1. 从Gitclone安装后，插件的文件夹名要改为yocool（虽然是安装插件常识，但是readme提一下比较好）
2. 如果是插件版，跳过复制yocool.py.example到config文件夹步骤的话，15行不是触发OSError，会先触发NameError，因为上一句10行的config没有被定义
3. 安装时私聊没有用，需要在群里at机器人安装

yocool用上了，感谢大佬开发插件_(:з」∠)_

**Comment by var-mixer** [comment]
1. 计划改成自动拼接路径，就不需要考虑命名了。
2. 不知道，问明见。
3. 此问题是用了HoshinoBot自带的`check_priv()`函数，此函数自动过滤群聊消息了。为什么这么写呢，因为[gacha](https://github.com/pcrbot/gacha)是这么写的......然后就抄过去了。

晚上改晚上改（
