### ISSUE TITLE
not found config of yocoolconsole

### ISSUE THREAD

**Issue by lzx722** [pcrbot/YoCool-Console#9]
试过将 config = hoshino.config.yocool.setup_config 改成 config = hoshino.config.YoCool-Console.setup_config，不过编译器貌似把 ‘YoCool-Console’ 当成  YoCool 减去 Console 了

**Comment by var-mixer** [comment]
百度随便搜的，引自[这里](http://c.biancheng.net/view/4186.html)：
> Python中标识符的命名不是随意的，而是要遵守一定的命令规则，比如说：
> * 标识符是由字符（A\~Z 和 a\~z）、下划线和数字组成，但第一个字符不能是数字。
> * 标识符不能和 Python 中的保留字相同。
> * Python中的标识符中，不能包含空格、@、% 以及 $ 等特殊字符。
> * 支持Unicode字符，例如中文，但是尽量不要用。

你该去学点Py基础知识。

**Comment by lzx722** [comment]
抱歉，我也是发了issues之后才意识到命名规则的问题，不好意思。。

现在的问题是，not found config of yocoolconsole，我看代码里写的是 config = hoshino.config.yocool.setup_config  ，以我对 hoshino 的config部分的理解，这里的yocool应该没有加载到（YoCool-Console和yocool两个我都弄了），hoshino的日志里也只提到加载了一个YoCool-Console

**Comment by var-mixer** [comment]
`not found config of  ******`是一行WARNING，不会引起致命错误，只是通知你`Hoshino`没有找到这个插件的配置文件。
但是`YoCool-Console`插件并不需要在`config`目录中放置一个额外的配置文件，并且就目前已开源的插件来看，大部分插件都不需要这样做。

**Comment by lzx722** [comment]
确实如此，现在新出的插件已经基本上将**.json放在当前插件目录了，但是这并不意味着YoCool-Console插件也是如此，Readme当中有提到，非插件版需要复制``YoCool-Console.py.example``到``config``文件夹，重命名为``YoCool-Console.py``，我照做之后给了我一个错误，``hoshino] ERROR: not found config of yocoolconsol``，若无视该错误强制安装，报错``FileNotFoundError: [Errno 2] No such file or directory: './hoshino/modules/yobot/yobot/src/client/public' ``

**Comment by var-mixer** [comment]
日，没注意，后来改名这部分不是我干的（快速甩锅）， @A-kirami 出来背锅。

**Comment by A-kirami** [comment]
已在新版本中修复该问题
